replicaCount: 3

image:
  repository: essence666/app_python_lab_2
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 3
  timeoutSeconds: 3
  failureThreshold: 3

nameOverride: ""
fullnameOverride: ""

secrets:
  secretKey: "change-me-secret-key"
  databasePassword: "change-me-db-password"

vault:
  enabled: false
  role: "app-python"
  secretPath: "secret/data/app-python/config"
  templateFormat: "env"

environment: "development"
logLevel: "info"

configmap:
  appName: "devops-info-service"
  environment: "development"
  featureFlags:
    enableMetrics: true
    enableDebugLogging: false
    enableRateLimit: false

persistence:
  enabled: true
  size: 100Mi
  storageClass: ""
  visitsFile: "/data/visits"

statefulset:
  enabled: false
  updateStrategy:
    type: RollingUpdate  # RollingUpdate or OnDelete
    partition: 0         # Only pods with ordinal >= partition are updated (RollingUpdate only)

rollout:
  enabled: true
  strategy: canary  # canary or blueGreen
  canary:
    steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause:
          duration: "30s"
      - setWeight: 60
      - pause:
          duration: "30s"
      - setWeight: 80
      - pause:
          duration: "30s"
  blueGreen:
    autoPromotionEnabled: false
    autoPromotionSeconds: null
  analysis:
    enabled: false
