replicaCount: 1

image:
  tag: "latest"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

service:
  type: NodePort
  nodePort: 30080

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8000

readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8000
