apiVersion: v2
name: app-go
description: Helm chart for the Go application
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - go
  - web
  - devops
maintainers:
  - name: essence-666
sources:
  - https://github.com/essence-666/DevOps-Core-Course
dependencies:
  - name: common-lib
    version: 0.1.0
    repository: "file://../common-lib"
